### ISSUE TITLE
3.6.0 incompatible with ManifestStaticFilesStorage (and probably CachedStaticFilesStorage too)

### ISSUE THREAD

**Issue by jdgoettsch** [django-cms/djangocms-text-ckeditor#474]
djangocms-text-ckeditor 3.6.0 calls `static` before the static files have been set up:

```python
$ python manage.py collectstatic
Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/envs/are.ucdavis.edu/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/envs/are.ucdavis.edu/lib/python3.6/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/usr/local/envs/are.ucdavis.edu/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/envs/are.ucdavis.edu/lib/python3.6/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/usr/local/envs/are.ucdavis.edu/lib/python3.6/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/envs/are.ucdavis.edu/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/envs/are.ucdavis.edu/lib/python3.6/site-packages/djangocms_blog/models.py", line 22, in <module>
    from djangocms_text_ckeditor.fields import HTMLField
  File "/usr/local/envs/are.ucdavis.edu/lib/python3.6/site-packages/djangocms_text_ckeditor/fields.py", line 8, in <module>
    from .widgets import TextEditorWidget
  File "/usr/local/envs/are.ucdavis.edu/lib/python3.6/site-packages/djangocms_text_ckeditor/widgets.py", line 21, in <module>
    class TextEditorWidget(Textarea):
  File "/usr/local/envs/are.ucdavis.edu/lib/python3.6/site-packages/djangocms_text_ckeditor/widgets.py", line 22, in TextEditorWidget
    class Media:
  File "/usr/local/envs/are.ucdavis.edu/lib/python3.6/site-packages/djangocms_text_ckeditor/widgets.py", line 25, in Media
    static(PATH_TO_JS),
  File "/usr/local/envs/are.ucdavis.edu/lib/python3.6/site-packages/django/contrib/admin/templatetags/admin_static.py", line 11, in static
    return _static(path)
  File "/usr/local/envs/are.ucdavis.edu/lib/python3.6/site-packages/django/templatetags/static.py", line 166, in static
    return StaticNode.handle_simple(path)
  File "/usr/local/envs/are.ucdavis.edu/lib/python3.6/site-packages/django/templatetags/static.py", line 117, in handle_simple
    return staticfiles_storage.url(path)
  File "/usr/local/envs/are.ucdavis.edu/lib/python3.6/site-packages/django/contrib/staticfiles/storage.py", line 162, in url
    return self._url(self.stored_name, name, force)
  File "/usr/local/envs/are.ucdavis.edu/lib/python3.6/site-packages/django/contrib/staticfiles/storage.py", line 141, in _url
    hashed_name = hashed_name_func(*args)
  File "/usr/local/envs/are.ucdavis.edu/lib/python3.6/site-packages/django/contrib/staticfiles/storage.py", line 432, in stored_name
    raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)
ValueError: Missing staticfiles manifest entry for 'djangocms_text_ckeditor/js/dist/bundle-45a646fecc.cms.ckeditor.min.js'
```

Django 1.11.12 and Django CMS 3.4.6:

```bash
$ pip freeze
aldryn-apphooks-config==0.4.1
aldryn-boilerplates==0.7.7
aldryn-common==1.0.4
-e git+git@github.com:jdgoettsch/aldryn-search.git@d9720a33ee6251d29e2ec86014af4eb998403f45#egg=aldryn_search
bleach==1.5.0
click==6.7
cmsplugin-filer==1.1.3
cycler==0.10.0
Django==1.11.12
django-appconf==1.0.2
django-appdata==0.2.0
django-auth-ldap==1.4.0
django-classy-tags==0.8.0
django-cms==3.4.6
django-compressor==2.2
django-contrib-comments==1.8.0
django-filer==1.3.0
django-formtools==2.1
django-haystack==2.8.1
django-meta==1.4.1
django-meta-mixin==0.3.0
django-mptt==0.8.7
-e git+git@github.com:jdgoettsch/django-parler.git@6d7f604752b5ffff2d70e1a53643ea8d4119b811#egg=django_parler
django-polymorphic==1.3
django-sekizai==0.10.0
django-sortedm2m==1.5.0
django-spurl==0.6.4
django-standard-form==1.1.1
django-taggit==0.22.2
django-taggit-autosuggest==0.3.3
django-taggit-templatetags==0.2.5
django-templatetag-sugar==1.0
django-treebeard==4.2.1
djangocms-admin-style==1.2.8
djangocms-apphook-setup==0.3.0
djangocms-attributes-field==0.3.0
djangocms-blog==0.9.5
djangocms-text-ckeditor==3.6.0
docutils==0.14
easy-thumbnails==2.4.2
et-xmlfile==1.0.1
first==2.0.1
gunicorn==19.7.1
html5lib==0.9999999
icalendar==4.0.1
jdcal==1.3
kiwisolver==1.0.1
lxml==4.2.1
matplotlib==2.2.2
numpy==1.14.2
openpyxl==2.5.2
Pillow==5.1.0
pip-tools==1.11.0
psycopg2-binary==2.7.4
pyasn1==0.4.2
pyasn1-modules==0.2.1
pyparsing==2.2.0
python-dateutil==2.7.2
python-ldap==3.0.0
python-memcached==1.59
pytz==2018.4
rcssmin==1.0.6
rjsmin==1.0.12
setproctitle==1.1.10
six==1.11.0
Unidecode==0.4.21
URLObject==2.4.3
Whoosh==2.7.4
xlrd==1.1.0
YURL==0.13
```

**Comment by pcolmant** [comment]
djangocms_text_ckeditor/js/dist/bundle-bca0d2d3f4.cms.ckeditor.min.js is present in self.hashed_files in django/contrib/staticfiles/storage.py - ManifestFilesMixin - stored_names(self, name) and not djangocms_text_ckeditor/js/dist/bundle-45a646fecc.cms.ckeditor.min.js

**Comment by pcolmant** [comment]
As workaround (...) : https://github.com/pcolmant/repanier/blob/master/repanier/big_blind_static.py

**Comment by macolo** [comment]
Its funny, but it works when django debug is True. Then, collectstatic can be run, and django debug can be set back to False. Subsequent runs then work fine, because the problematic files are then already included in the staticfiles.json.

**Comment by macolo** [comment]
Mostly unrelated note for subsequent Google searches: ManifestStaticFilesStorage requires apps to be listed in INSTALLED_APPS

**Comment by afs2015** [comment]
@pcolmant: Your workaround solution worked great, thank you for your work!

**Comment by robotiguy** [comment]
@pcolmant where are you putting this file in the django ecosystem?

**Comment by merwok** [comment]
It’s a module that could live anywhere in your project, the important part is to configure the storage class in settings: https://github.com/pcolmant/repanier/blob/master/mysite/common_settings.py#L156

**Comment by TZanke** [comment]
The Issue still exists in Version 4.0.0:
`Post-processing 'djangocms_text_ckeditor/js/dist/bundle-bb31a8b837.cms.ckeditor.min.js' failed!`
```
ValueError: The file 'djangocms_text_ckeditor/js/dist/contents.css' could not be found with...ManifestStaticFilesStorage.
```

Right now also `django-ckeditor` has the same issue with `ManifestStaticFilesStorage`, see: 
https://github.com/django-ckeditor/django-ckeditor/issues/675

If you use the custom `ManifestStaticFilesStorage` from the other Issue you can replace `ckeditor/ckeditor` with `djangocms_text_ckeditor/ckeditor` and also add the line ```name = name.replace('djangocms_text_ckeditor/js/dist/', 'djangocms_text_ckeditor/ckeditor/')```
Now `ManifestStaticFilesStorage` is working with _djangocms-text-ckeditor_

Not great, but also not a issue of _djangocms-text-ckeditor_ itself. But maybe would be easier to add a fix in the future if _djangocms-text-ckeditor_ would require django-jquery instead of supplying its own ck files. But i am not a _djangocms-text-ckeditor_ expert.

Best regards

**Comment by merwok** [comment]
it should be fixed though

**Comment by merwok** [comment]
keep it open

**Comment by fsbraun** [comment]
I believe this is fixed (we're at version 5 now). Does anyone still have this issue?

**Comment by jdgoettsch** [comment]
Working for me know on Django 3.2.20, Django CMS 3.11.3, and djangocms-text-ckeditor 5.1.3.

**Comment by merwok** [comment]
People need ckeditor and manifest static storage
