### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'properties')

### ISSUE THREAD

**Issue by DmytroLitvinov** [django-cms/djangocms-text-ckeditor#600]
Hi there,

After updating the library from v4.0.0 to v5.0.0 I receive the next error in my project:

```
bundle-bb31a8b837.cms.ckeditor.min.js:11410 Uncaught TypeError: Cannot read properties of undefined (reading 'properties')
    at Object.init (bundle-bb31a8b837.cms.ckeditor.min.js:11410:224)
    at Object.<anonymous> (bundle-bb31a8b837.cms.ckeditor.min.js:3908:52)
    at e (bundle-bb31a8b837.cms.ckeditor.min.js:3603:52)
    at Object.load (bundle-bb31a8b837.cms.ckeditor.min.js:3607:25)
    at bundle-bb31a8b837.cms.ckeditor.min.js:3901:48
    at CKEDITOR.resourceManager.<anonymous> (bundle-bb31a8b837.cms.ckeditor.min.js:3743:41)
    at CKEDITOR.resourceManager.<anonymous> (bundle-bb31a8b837.cms.ckeditor.min.js:3710:28)
    at e (bundle-bb31a8b837.cms.ckeditor.min.js:3603:52)
    at Object.load (bundle-bb31a8b837.cms.ckeditor.min.js:3607:25)
    at CKEDITOR.resourceManager.load (bundle-bb31a8b837.cms.ckeditor.min.js:3700:40)
```

Here where it is failed in minified file:
> .... && a.addMenuItems({ flash: { label: a.lang.flash.properties,    .....
   
   
@marksweb , any advice on what it can be? Maybe https://github.com/django-cms/djangocms-text-ckeditor/pull/593/files is related to it? 

cc @vinitkumar

**Comment by marksweb** [comment]
Fixed in 5.0.1
