### ISSUE TITLE
Crashing Ckeditor with Latest Release 5.0.1

### ISSUE THREAD

**Issue by vinitkumar** [django-cms/djangocms-text-ckeditor#602]
We get this crash on production for our websites.

```js
Uncaught TypeError: Cannot read properties of undefined (reading 'replace')
    at b (bundle-fb7663a06e.cms.ckeditor.min.js:775:406)
    at Object.init (bundle-fb7663a06e.cms.ckeditor.min.js:777:16)
    at Object.<anonymous> (bundle-fb7663a06e.cms.ckeditor.min.js:286:426)
    at w (bundle-fb7663a06e.cms.ckeditor.min.js:265:193)
    at Array.x (bundle-fb7663a06e.cms.ckeditor.min.js:265:336)
    at z (bundle-fb7663a06e.cms.ckeditor.min.js:265:420)
    at bundle-fb7663a06e.cms.ckeditor.min.js:266:360
```

Here is our ckeditor settings

```python
CKEDITOR_SETTINGS = {
    "language": "{{ language }}",
    "toolbar": "CMS",
    "toolbar_CMS": [
        ["Undo", "Redo"],
        ["cmsplugins", "cmswidget", "-", "ShowBlocks"],
        ["Format", "Styles"],
        ["Link", "Unlink", "Anchor"],
        ["Maximize", ""],
        "/",
        [
            "Bold",
            "Italic",
            "Underline",
            "-",
            "Subscript",
            "Superscript",
            "-",
            "RemoveFormat",
        ],
        ["JustifyLeft", "JustifyCenter", "JustifyRight", "JustifyBlock"],
        ["HorizontalRule"],
        ["NumberedList", "BulletedList", "-", "Outdent", "Indent", "-", "Table"],
        ["Source"],
     ]
}       
```

I think it might have to do with the language settings and some people have not got this error if they don't have this setting.

**Comment by vinitkumar** [comment]
@fsbraun You are right. We talked about this. Also, this has nothing to do with the ckeditor doing anything wrong. Actually, we have overridden a tonne of the ckeditor plugins in our static directory. Now, since we updated to the latest version of djangocms-text-ckeditor, those plugins got left behind and were incompatible.
